### ISSUE TITLE
Improve materials for WebGL rendering

### ISSUE THREAD

**Issue by fragmuffin** [fragmuffin/cqparts#36]
The exported materials look either washed out, or too dark.
Need to play with some pbr factors, or prescribe a render method (or both).

* [ ] Change part `_render` parameter to `_material`
* [ ] Document a baseline for WebGL
    * scene lighting
    * element material properties
    * code example for three.js
    * code example for a-frame

Some materials examples:
* MeshPhongMaterial: https://codepen.io/dpdknl/pen/KvBjmP
* MeshToonMaterial: https://codepen.io/davidlyons/pen/GOzQyG

**Comment by fragmuffin** [comment]
## Task List
* [ ] Change part `_render` parameter to `_material`
* [ ] Document a baseline for WebGL
    * scene lighting
    * element material properties
    * code example for three.js
    * code example for a-frame

**Comment by fragmuffin** [comment]
taging @RustyVermeer
